#!/bin/ksh
DIST=/opt/dkmon/dist/
cd $DIST || { echo "/opt/dkmon/dist/"; exit 1; }
latest_tar=`/bin/ls -1tr dkmon*.tar.gz|tail -1`
out_of_date=`find . -maxdepth 1 -name ${latest_tar%%-bin.tar.gz} ! -newer $latest_tar`
[ ! -d ${latest_tar%%-bin.tar.gz} -o -n "$out_of_date" ]&& { echo -n "Installing.."; tar zxf $latest_tar; echo "..OK"; }
wd=`pwd`
cp=`find . -name \*.jar|xargs echo|sed -e 's/ /:/g' -e "s:\./:$wd/:g"`
mkdir -p resources ../log
log_file=${wd%/*}/log/Simulator
cat <<EOF > resources/log4j.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration debug="true"
	xmlns:log4j='http://jakarta.apache.org/log4j/'>

	<appender name="console" class="org.apache.log4j.ConsoleAppender">
	    <layout class="org.apache.log4j.PatternLayout">
		<param name="ConversionPattern" 
		  value="%d{yyyy-MM-dd HH:mm:ss} %-5p %t %c{1}:LINE %L %m%n" />
	    </layout>
	</appender>

	<appender name="ROLL" class="org.apache.log4j.rolling.RollingFileAppender">
		<param name="file" value="$log_file.log" />
		<param name="append" value="true" />
		<param name="encoding" value="UTF-8" />

		<rollingPolicy class="org.apache.log4j.rolling.TimeBasedRollingPolicy">
			<!-- The file to roll to, this is a fairly intelligent parameter, if the file
			ends in .gz, it gzips it, based on the date stamp it rolls at that time, 
			default is yyyy-MM-dd, (rolls at midnight)
			See: http://logging.apache.org/log4j/companions/extras/apidocs/org/apache/log4j/rolling/TimeBasedRollingPolicy.html -->
			<param name="FileNamePattern" value="$log_file.%d.log.gz" />
		</rollingPolicy>

		<layout class="org.apache.log4j.PatternLayout">
			<param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss}|%-5p|%t|%c{1} LINE %L|%m%n" />
	    </layout>
	</appender>

	<root>
		<level value="DEBUG" />
		<appender-ref ref="console" />
		<appender-ref ref="ROLL" />
	</root>

</log4j:configuration>
EOF

[ -t ]||exec >/dev/null 2>&1

java -cp resources/:$cp com/dkay29/load/sim/Simulator "${@}"
